[package]
name = "AoC-Utils"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.22", features = ["derive"] }
reqwest = "0.12.9"
tokio = { version = "1.42.0", features = ["full"] }
